package eu.mycellium.android

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import java.io.File
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import uniffi.mycellium_sdk.SdkException
import uniffi.mycellium_sdk.SecretStore

/**
 * The Android adapter for the SDK's [SecretStore] seam (issue #65).
 *
 * The Android Keystore does not store arbitrary secrets well — it stores *keys*.
 * So this uses the **envelope** pattern from `docs/research/SECURE-STORAGE.md`
 * §2.1:
 *
 *  - A single non-exportable **AES-256-GCM wrapping key** lives in the
 *    `AndroidKeyStore` provider (hardware-backed via TEE / StrongBox where the
 *    device supports it). The raw key bytes never leave the secure hardware.
 *  - Each secret the SDK hands us (today just the ~64-byte identity under the
 *    key `"identity"`) is sealed with that wrapping key. We persist only the
 *    resulting `[iv | ciphertext+tag]` blob in app-private storage
 *    (`filesDir/secretstore/`, which is already app-sandboxed and excluded from
 *    backup — see AndroidManifest + res/xml backup rules).
 *
 * `store` = wrap + write. `load` = read + unwrap. `delete` = delete the blob
 * (the shared wrapping key is left in place).
 *
 * **Fail-closed contract** (SECURE-STORAGE.md §6, and the SDK's own doc on the
 * trait): `load` returns `null` ONLY for a genuinely absent key. Any real
 * failure — a corrupt/truncated blob, an AEAD tag mismatch, the Keystore being
 * unavailable — throws an [SdkException] instead of returning `null`, so the SDK
 * never mistakes an unreadable identity for "no identity" and silently generates
 * a fresh one that would orphan the account.
 *
 * ## Residual limits (state them plainly; never claim "unstealable")
 * This raises the bar from "read a file" to "defeat the platform's key
 * protection", but it does NOT protect against:
 *  - a **rooted device with the screen unlocked**, where an attacker running as
 *    this app can ask the Keystore to unwrap the blob (gate unwrap on
 *    biometrics/PIN via `setUserAuthenticationRequired(true)` if you want a
 *    "lock the app" UX — deliberately omitted here so background `sync()` works);
 *  - a **backup** that captures the wrapped blob — which is why it is excluded
 *    from Auto Backup / device transfer (SECURE-STORAGE.md §5). StrongBox raises
 *    the cost; TEE-only is weaker.
 *
 * Losing the device (and thus this at-rest key) is recoverable WITHOUT ever
 * exporting the raw secret: the account is re-bound from a fresh device by email
 * verification (issue #6).
 */
class AndroidKeystoreSecretStore(
    context: Context,
    /**
     * Isolates this store's blobs under `secretstore/<namespace>/`. Leave empty
     * for a single-account app; give distinct namespaces if one app process holds
     * more than one account (e.g. account switching, or an in-process test with
     * two clients) so their `"identity"` secrets don't collide.
     */
    private val namespace: String = "",
) : SecretStore {

    private val appContext = context.applicationContext

    /** Per-key sealed blobs live here, one file per SDK key. */
    private val blobDir: File by lazy {
        val base = File(appContext.filesDir, BLOB_DIR)
        val dir = if (namespace.isEmpty()) {
            base
        } else {
            // Base64-url-encode the namespace to a safe directory name (same
            // scheme as blob filenames), so any string is a valid, collision-free dir.
            val safe = Base64.encodeToString(
                namespace.toByteArray(Charsets.UTF_8),
                Base64.URL_SAFE or Base64.NO_PADDING or Base64.NO_WRAP,
            )
            File(base, safe)
        }
        dir.apply { mkdirs() }
    }

    override fun store(key: String, secret: ByteArray) {
        try {
            val cipher = Cipher.getInstance(TRANSFORMATION).apply {
                init(Cipher.ENCRYPT_MODE, wrappingKey())
            }
            val iv = cipher.iv // GCM: 12 bytes, generated by the provider.
            val ciphertext = cipher.doFinal(secret)

            // Layout: [1-byte iv length][iv][ciphertext+tag].
            val blob = ByteArray(1 + iv.size + ciphertext.size)
            blob[0] = iv.size.toByte()
            System.arraycopy(iv, 0, blob, 1, iv.size)
            System.arraycopy(ciphertext, 0, blob, 1 + iv.size, ciphertext.size)

            writeAtomically(blobFile(key), blob)
        } catch (e: SdkException) {
            throw e
        } catch (e: Throwable) {
            // Could not durably seal/persist -> fatal, per the fail-closed rule.
            throw SdkException.Storage("keystore store failed: ${e.javaClass.simpleName}")
        }
    }

    override fun load(key: String): ByteArray? {
        val file = blobFile(key)
        // Genuinely absent -> the ONLY null return.
        if (!file.exists()) return null

        val blob: ByteArray
        val secretKey: SecretKey
        try {
            blob = file.readBytes()
            secretKey = wrappingKey()
        } catch (e: Throwable) {
            // Read/keystore failure on a key that DOES exist -> fail closed.
            throw SdkException.Storage("keystore load failed: ${e.javaClass.simpleName}")
        }

        try {
            if (blob.isEmpty()) throw IllegalStateException("empty blob")
            val ivLen = blob[0].toInt() and 0xFF
            if (ivLen <= 0 || 1 + ivLen > blob.size) throw IllegalStateException("bad iv length")
            val iv = blob.copyOfRange(1, 1 + ivLen)
            val ciphertext = blob.copyOfRange(1 + ivLen, blob.size)

            val cipher = Cipher.getInstance(TRANSFORMATION).apply {
                init(Cipher.DECRYPT_MODE, secretKey, GCMParameterSpec(GCM_TAG_BITS, iv))
            }
            return cipher.doFinal(ciphertext)
        } catch (e: Throwable) {
            // Corrupt blob or AEAD tag mismatch -> fail closed, do NOT return null.
            throw SdkException.Crypto("keystore secret is unreadable or corrupt")
        }
    }

    override fun delete(key: String) {
        try {
            val file = blobFile(key)
            if (file.exists() && !file.delete()) {
                throw IllegalStateException("delete returned false")
            }
            // The shared wrapping key is intentionally left in place.
        } catch (e: Throwable) {
            throw SdkException.Storage("keystore delete failed: ${e.javaClass.simpleName}")
        }
    }

    /** Fetch the AES wrapping key from the AndroidKeyStore, creating it once. */
    private fun wrappingKey(): SecretKey {
        val ks = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        (ks.getEntry(KEY_ALIAS, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }
        return generateWrappingKey()
    }

    private fun generateWrappingKey(): SecretKey {
        val generator = KeyGenerator.getInstance(
            KeyProperties.KEY_ALGORITHM_AES,
            ANDROID_KEYSTORE,
        )
        val builder = KeyGenParameterSpec.Builder(
            KEY_ALIAS,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(256)
            // No setRandomizedEncryptionRequired(false): keep the provider-random
            // IV (the default), which is what we persist alongside the ciphertext.

        // Prefer the StrongBox secure element when the device has one (API 28+);
        // fall back to the TEE-backed key if not available.
        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.P) {
            try {
                generator.init(builder.setIsStrongBoxBacked(true).build())
                return generator.generateKey()
            } catch (e: android.security.keystore.StrongBoxUnavailableException) {
                // Fall through to a TEE-backed key below.
            } catch (e: Throwable) {
                // Some devices advertise but mis-handle StrongBox; fall back.
            }
            // The Builder is mutable and shared, so the attempt above left
            // `isStrongBoxBacked = true` on it — turn it back OFF, or the fallback
            // build() re-requests StrongBox and throws again on every device (and
            // every emulator) that lacks the secure element. Only reachable on
            // API 28+, so calling this setter here is safe (it was added in 28).
            builder.setIsStrongBoxBacked(false)
        }
        generator.init(builder.build())
        return generator.generateKey()
    }

    /** Map an arbitrary SDK key string to a safe filename. */
    private fun blobFile(key: String): File {
        val name = Base64.encodeToString(
            key.toByteArray(Charsets.UTF_8),
            Base64.URL_SAFE or Base64.NO_PADDING or Base64.NO_WRAP,
        )
        return File(blobDir, "$name.blob")
    }

    private fun writeAtomically(target: File, bytes: ByteArray) {
        val tmp = File(target.parentFile, target.name + ".tmp")
        tmp.writeBytes(bytes)
        if (!tmp.renameTo(target)) {
            // renameTo can fail if the target exists on some filesystems.
            target.delete()
            if (!tmp.renameTo(target)) {
                tmp.delete()
                throw IllegalStateException("atomic rename failed")
            }
        }
    }

    private companion object {
        const val ANDROID_KEYSTORE = "AndroidKeyStore"
        const val KEY_ALIAS = "eu.mycellium.identity.wrapkey"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val GCM_TAG_BITS = 128
        const val BLOB_DIR = "secretstore"
    }
}
